/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CodebreakerRouteImport } from './routes/codebreaker'
import { Route as CodemakerRouteImport } from './routes/codemaker'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodebreakerRoute = CodebreakerRouteImport.update({
  id: '/codebreaker',
  path: '/codebreaker',
  getParentRoute: () => rootRouteImport,
} as any)
const CodemakerRoute = CodemakerRouteImport.update({
  id: '/codemaker',
  path: '/codemaker',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/codebreaker': typeof CodebreakerRoute
  '/codemaker': typeof CodemakerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/codebreaker': typeof CodebreakerRoute
  '/codemaker': typeof CodemakerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/codebreaker': typeof CodebreakerRoute
  '/codemaker': typeof CodemakerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/codebreaker' | '/codemaker'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/codebreaker' | '/codemaker'
  id: '__root__' | '/' | '/codebreaker' | '/codemaker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodebreakerRoute: typeof CodebreakerRoute
  CodemakerRoute: typeof CodemakerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codebreaker': {
      id: '/codebreaker'
      path: '/codebreaker'
      fullPath: '/codebreaker'
      preLoaderRoute: typeof CodebreakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codemaker': {
      id: '/codemaker'
      path: '/codemaker'
      fullPath: '/codemaker'
      preLoaderRoute: typeof CodemakerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodebreakerRoute: CodebreakerRoute,
  CodemakerRoute: CodemakerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
